plugin-enabled-for: main-hand
check-interval-ticks: 20
default-options:
  amplifier: 0
  ambient-particles: true
  main-particles: true
main-hand:
  DIAMOND: GLOWING
  ELYTRA: LEVITATION:1:false:true
  GHAST_TEAR:
  - GLOWING
  - LEVITATION
off-hand:
  GHAST_TEAR: INVISIBILITY
  COAL: FIRE_RESISTANCE:2
